### ISSUE TITLE
[BUG] Difficulty in updating meta data due to the "&" character

### ISSUE THREAD

**Issue by s6sapolw** [UNDP-Data/geohub#1582]
### Bug Description

For the following datasets, it is difficult to update the meta data.
![image](https://user-images.githubusercontent.com/101448516/225920471-65e6d1d9-1c5b-4776-b071-f54a2ab24f7b.png)

### Bug Reproduction

Visit the Manage datasets page in the GeoHub and enter the names of the aforementioned data and click on edit metadata.

### Bug Impact

Difficulty in updating the metadata.

### Bug Screenshots

Even after updating the meta data as you can see in figure 1, still it does not update the licence information.
Figure 1:
![image](https://user-images.githubusercontent.com/101448516/225921158-e501cbed-d602-4000-b5ee-6d70fe09ad4a.png)

Figure 2:
![image](https://user-images.githubusercontent.com/101448516/225921354-cb56ac6a-705f-446b-b486-d2c10b579884.png)

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1201759936) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
https://dev.undpgeohub.org/data?queryoperator=and&operator=and&sortby=updatedat%2Cdesc&limit=100&offset=0&type=azure&mydata=true&query=Tropical+Cyclonic+Wind

**Comment by JinIgarashi** [comment]
should be able to be solved by this procedure

https://github.com/UNDP-Data/geohub/issues/1511

**Comment by s6sapolw** [comment]
I have published the above four datasets.
Thank you for resolving the issue

**Comment by Thuhaa** [comment]
Reopening as bug is still there
![image](https://user-images.githubusercontent.com/45137948/230936200-c7525cd2-6044-444c-b338-60b5b52ce489.png)

**Comment by Thuhaa** [comment]
Reopening as bug is still there
![image](https://user-images.githubusercontent.com/45137948/230936200-c7525cd2-6044-444c-b338-60b5b52ce489.png)

**Comment by JinIgarashi** [comment]
@Thuhaa 
See my comment here.
https://github.com/UNDP-Data/geohub/pull/1643#issuecomment-1508097259

Please ask @iferencik for further advise.

**Comment by s6sapolw** [comment]
The issue is resolved with the ability to publish.
